# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bif < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "0.0.11"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.11/bif_0.0.11_darwin_arm64.tar.gz"
      sha256 "76f7ff872c1107e2cc43b34bf17924896397c31c732063bdd701aaa983164908"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.11/bif_0.0.11_darwin_amd64.tar.gz"
      sha256 "0465b240e74cc361f8fae0ddbf40e9aecbfd54e2080213c34dd674b8347a6058"

      def install
        bin.install "bif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.11/bif_0.0.11_linux_arm64.tar.gz"
      sha256 "9ec6e9b46092585c966d48475624a21831b0aab3e791f3ee471fa483bc3be2e4"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.11/bif_0.0.11_linux_amd64.tar.gz"
      sha256 "375b2167c9375af04e1e0a1b560a2592db39ab94f37fcfd23e8d23cfe71e8867"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.11/bif_0.0.11_linux_armv6.tar.gz"
      sha256 "5df9f5c672396434cabc421fffe8cb5c8411a9ac0b17c9ecc1e39028787eeb05"

      def install
        bin.install "bif"
      end
    end
  end

  test do
    system "#{bin}/bif version"
  end
end
