# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bif < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.3/bif_0.0.3_darwin_amd64.tar.gz"
      sha256 "7287898966b549c0d7b2a512a755fd2620a183c8b44871525ccf4def4ea0f113"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.3/bif_0.0.3_darwin_arm64.tar.gz"
      sha256 "8e1af29fed953d61b70f3fdf1b2cba042744402d67defceeb6c1b9247cf24d96"

      def install
        bin.install "bif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.3/bif_0.0.3_linux_armv6.tar.gz"
      sha256 "87177ce7a8bf6d611fd58f2fc1a40672e07277aa739394496717a99df2f8b48d"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.3/bif_0.0.3_linux_arm64.tar.gz"
      sha256 "bff91a77cb614d8f4425e706ea731d9a6aa358c625405f128b4c825e30f80767"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.3/bif_0.0.3_linux_amd64.tar.gz"
      sha256 "ccc18c18e3c5ecc1ea97f45db6466063721b18566967849de3fa1e624865ca2a"

      def install
        bin.install "bif"
      end
    end
  end

  test do
    system "#{bin}/bif version"
  end
end
