# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bif < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.2/bif_0.0.2_darwin_arm64.tar.gz"
      sha256 "959a0c0183b0af7e27640fcc9d4b60a605a407b20b9fa45abde3b3916b506ec4"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.2/bif_0.0.2_darwin_amd64.tar.gz"
      sha256 "82812081f2ace11289ca7f46d00fa96e8fd5426d0a493861d66f4c4457570e97"

      def install
        bin.install "bif"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.2/bif_0.0.2_linux_arm64.tar.gz"
      sha256 "0793fb98a7a09485d49d64d02dfeb3e98b54c4f1d1609cad81f4cebb440aed28"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.2/bif_0.0.2_linux_amd64.tar.gz"
      sha256 "5d86e86cd43367309a8c648749be84c45ba1689c38999553592fec6f127d9a8c"

      def install
        bin.install "bif"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/bif/releases/download/v0.0.2/bif_0.0.2_linux_armv6.tar.gz"
      sha256 "c5428d83927883456b724d099d701726b43e71bd5063e2e7f725536d577b3f0b"

      def install
        bin.install "bif"
      end
    end
  end

  test do
    system "#{bin}/bif version"
  end
end
