# This file was generated by GoReleaser. DO NOT EDIT.
class FairwindsOps < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/pluto/releases/download/v1.0.1/pluto_1.0.1_darwin_amd64.tar.gz"
    sha256 "1000099d42d2d426997d39c24d03583c46a2d8f8401e6030bb4bc099aaf27cd1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/pluto/releases/download/v1.0.1/pluto_1.0.1_linux_amd64.tar.gz"
      sha256 "61eecab5a7e63b6230b955771de406acd5843396b6e012652180f5c010492b48"
    end
  end

  def install
    bin.install "pluto"
  end

  test do
    system "#{bin}/pluto version"
  end
end
