# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FwHealthChecker < Formula
  desc "Monitor client AWS account health"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/fw-health-checker/releases/download/v0.1.0/fw-health-checker_0.1.0_darwin_amd64.tar.gz"
      sha256 "d00b020aa812068a56b6f1aedfa87c505fbdfe92fbb4d8c7e790ad0ce88ac076"

      define_method(:install) do
        bin.install "fw-health-checker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/fw-health-checker/releases/download/v0.1.0/fw-health-checker_0.1.0_darwin_arm64.tar.gz"
      sha256 "830d0bc61b8882e79510c2b6347f6e71bdcfb6fcfb6688fa750a0175079ed887"

      define_method(:install) do
        bin.install "fw-health-checker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/fw-health-checker/releases/download/v0.1.0/fw-health-checker_0.1.0_linux_amd64.tar.gz"
      sha256 "9b7ff841693c7deb46956770451290aaa3260664718b1982a601df8d8097c3d6"
      define_method(:install) do
        bin.install "fw-health-checker"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/fw-health-checker/releases/download/v0.1.0/fw-health-checker_0.1.0_linux_armv6.tar.gz"
      sha256 "ce50b9812ab7bbf7bfeb71f00d93f42cc6c278f39da36535dba57fd945380a2e"
      define_method(:install) do
        bin.install "fw-health-checker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/fw-health-checker/releases/download/v0.1.0/fw-health-checker_0.1.0_linux_arm64.tar.gz"
      sha256 "3f2b13e2a2872220f6af70078362fd5af6cd358863a30fdd07cb82c80c2918e4"
      define_method(:install) do
        bin.install "fw-health-checker"
      end
    end
  end

  test do
    system "#{bin}/fw-health-checker version"
  end
end
