# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemini < Formula
  desc "Open Source Best Practices for Kubernetes"
  homepage ""
  version "2.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/gemini/releases/download/2.0.0/gemini_darwin_arm64.tar.gz"
      sha256 "496a2ff02ecc5692fd08e0ff26b6d67a55ea68be68e1e3606ee35df78c6a17c2"

      def install
        bin.install "gemini"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gemini/releases/download/2.0.0/gemini_darwin_amd64.tar.gz"
      sha256 "48a64b2c201d271de63618f65cbd1892dbd4af8dce688beca29e38d6008ba7b1"

      def install
        bin.install "gemini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gemini/releases/download/2.0.0/gemini_linux_amd64.tar.gz"
      sha256 "d7075482d2565c93023dd95f5f5351ff569932e0331aece167ac0f2a04b2f8e5"

      def install
        bin.install "gemini"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gemini/releases/download/2.0.0/gemini_linux_armv6.tar.gz"
      sha256 "cf3e7780653b6d7983d245da9f035baf7b44cca5ef3e773c16959fd137eca51c"

      def install
        bin.install "gemini"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gemini/releases/download/2.0.0/gemini_linux_arm64.tar.gz"
      sha256 "87a59e5cb5930cece736d37f08fe99df0aad8ad6190ca9649e660659514e60db"

      def install
        bin.install "gemini"
      end
    end
  end

  test do
    system "#{bin}/gemini version"
  end
end
