# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemini < Formula
  desc "Open Source Best Practices for Kubernetes"
  homepage ""
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gemini/releases/download/v2.1.0/gemini_2.1.0_darwin_amd64.tar.gz"
      sha256 "394fa3d2d2c1b1357de7551f67b8be8c83321b41de483fd5de8be774976dc378"

      define_method(:install) do
        bin.install "gemini"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/gemini/releases/download/v2.1.0/gemini_2.1.0_darwin_arm64.tar.gz"
      sha256 "550ac2d90c8ee71910708450f378c7e4ed1dd1a66efdd5c887e0f092d4d3a431"

      define_method(:install) do
        bin.install "gemini"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gemini/releases/download/v2.1.0/gemini_2.1.0_linux_amd64.tar.gz"
      sha256 "9f974e16469b2a111e7d2dff387f0318cd9126047a3af1b8687e5033afd57012"
      define_method(:install) do
        bin.install "gemini"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gemini/releases/download/v2.1.0/gemini_2.1.0_linux_armv6.tar.gz"
      sha256 "ca2faf5b736b25ac6675a2bf8ef2e8730f8ec1158b4df63555d33ed928e8aefa"
      define_method(:install) do
        bin.install "gemini"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gemini/releases/download/v2.1.0/gemini_2.1.0_linux_arm64.tar.gz"
      sha256 "043d44e753402e997a4505611944cf0517087b2fabbb7a16d9c266a9b82d6d41"
      define_method(:install) do
        bin.install "gemini"
      end
    end
  end

  test do
    system "#{bin}/gemini version"
  end
end
