# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goldilocks < Formula
  desc "Kubernetes workload resource usage analysis"
  homepage ""
  version "4.16.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.16.2/goldilocks_4.16.2_darwin_amd64.tar.gz"
      sha256 "ccf4d57237bfa74a77bb575e8d408e5d89a350e988217a5eecc790365cec9d9a"

      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.16.2/goldilocks_4.16.2_darwin_arm64.tar.gz"
      sha256 "5ad5dcfa3ed9e1540127c3e8e6c5b31a42871cfe831585c683f69c7475f21aa5"

      define_method(:install) do
        bin.install "goldilocks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.16.2/goldilocks_4.16.2_linux_amd64.tar.gz"
      sha256 "b2599d9c724a9147667e76a7e1d1b600143f55b83855ffdec275f2bf3bb484a7"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.16.2/goldilocks_4.16.2_linux_armv6.tar.gz"
      sha256 "c30e34fc45cf4847b2c88da99493cd3071d29dfbc4720477b2680d4d7cb590fa"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.16.2/goldilocks_4.16.2_linux_arm64.tar.gz"
      sha256 "ca9df1d18cdff85f3ea242df93f3905cc9d0a4d381ba820620fdf2939f705c10"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
  end

  test do
    system "#{bin}/goldilocks version"
  end
end
