# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goldilocks < Formula
  desc "Kubernetes workload resource usage analysis"
  homepage ""
  version "4.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.15.0/goldilocks_4.15.0_darwin_amd64.tar.gz"
      sha256 "9a2f8211265b6afad22e10bd8fc57111ac499ec73386d27d73e6aa43e8283dcb"

      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.15.0/goldilocks_4.15.0_darwin_arm64.tar.gz"
      sha256 "2e2c85506a80fd0a3c5c9ae5fa7197b10e4c3283eadcd1e3ebea79d09e9d32ba"

      define_method(:install) do
        bin.install "goldilocks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.15.0/goldilocks_4.15.0_linux_amd64.tar.gz"
      sha256 "a1d780c8010cde55e773d96ad2dba2d551143e721c779bdec5b2bee8c18ff565"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.15.0/goldilocks_4.15.0_linux_armv6.tar.gz"
      sha256 "462b14120db75b23c6eb64d065ad45f2b6d9c447824cc384e9d642bf8cbda569"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/goldilocks/releases/download/v4.15.0/goldilocks_4.15.0_linux_arm64.tar.gz"
      sha256 "2c36893fc856debd20c822e03d79f6ff6ff24038fe8d01aee963fb944e958260"
      define_method(:install) do
        bin.install "goldilocks"
      end
    end
  end

  test do
    system "#{bin}/goldilocks version"
  end
end
