# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonogo < Formula
  desc "Check cluster addons for upgrade confidence"
  homepage ""
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.2/gonogo_0.2.2_darwin_arm64.tar.gz"
      sha256 "9da2a4a7ac3b09d7ceca053063abba8d2fdb19128be8071c203ec8be832656c8"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.2/gonogo_0.2.2_darwin_amd64.tar.gz"
      sha256 "c0e3e43e5e9ae8d4eacd1b24a3dce8c88417f8f8c5282e206cd6440ee73a9a4e"

      def install
        bin.install "gonogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.2/gonogo_0.2.2_linux_armv6.tar.gz"
      sha256 "1e08506b5abfccc2e23143129a2ed11f7aab3cf96428fb1dd090c16d88055c2d"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.2/gonogo_0.2.2_linux_arm64.tar.gz"
      sha256 "6242e13099f9841b99637857ea465c90e513021a008677e34fdc080060e12300"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.2/gonogo_0.2.2_linux_amd64.tar.gz"
      sha256 "13cce09b06ec347dddd0e38551895bfe3587eef9af5d64ac13ca31775cfea7f7"

      def install
        bin.install "gonogo"
      end
    end
  end

  test do
    system "#{bin}/gonogo version"
  end
end
