# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonogo < Formula
  desc "Check cluster addons for upgrade confidence"
  homepage ""
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.3.1/gonogo_0.3.1_darwin_arm64.tar.gz"
      sha256 "b5ae247b7f78f2638c6682f25045f430d6af3f4211124ea939822a6a8eed7156"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.3.1/gonogo_0.3.1_darwin_amd64.tar.gz"
      sha256 "db6b22ee5df9e0c4d9fd69b1de09613e5768006261f34217c6e95a8d5372c50e"

      def install
        bin.install "gonogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.3.1/gonogo_0.3.1_linux_arm64.tar.gz"
      sha256 "4034d5aa4aad256bfaaa398d0e9f78f9fa849b766b57a23e4e646f02914ce1c3"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.3.1/gonogo_0.3.1_linux_amd64.tar.gz"
      sha256 "50d51cd581d021c560af7ae07bef3aa4b7dcaf13660d3e457a3d2b0db02e89fe"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.3.1/gonogo_0.3.1_linux_armv6.tar.gz"
      sha256 "c9df4e7d1eba0f30a6f4b0a0a18ce2b917296ab70a681982798a71ca478e1ced"

      def install
        bin.install "gonogo"
      end
    end
  end

  test do
    system "#{bin}/gonogo version"
  end
end
