# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonogo < Formula
  desc "Check cluster addons for upgrade confidence"
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.0/gonogo_0.2.0_darwin_arm64.tar.gz"
      sha256 "62b5c097e711a8327797bae34ebcb6be6489e1793c038e1f313b52c9c67e44bc"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.0/gonogo_0.2.0_darwin_amd64.tar.gz"
      sha256 "0005a7bf396922c062157e905ed3d9172f607831158bb56b4ffa709d7ddd24f8"

      def install
        bin.install "gonogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.0/gonogo_0.2.0_linux_armv6.tar.gz"
      sha256 "d6cdd192f40443c85a2d6124d259d5c210dde836374b15a3cd837825a7cae504"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.0/gonogo_0.2.0_linux_arm64.tar.gz"
      sha256 "ce48010b8118c6433dfade5c77e5d85f308992fc04849c846caa3d9f5107e1c8"

      def install
        bin.install "gonogo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/gonogo/releases/download/v0.2.0/gonogo_0.2.0_linux_amd64.tar.gz"
      sha256 "f42472897694358e93ff7f2b54de6c9cb748dac96485220e15e3b82a4a44c85b"

      def install
        bin.install "gonogo"
      end
    end
  end

  test do
    system "#{bin}/gonogo version"
  end
end
