# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmReleasePruner < Formula
  desc "Automatically delete old Helm releases"
  homepage ""
  version "4.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.0.4/helm-release-pruner_4.0.4_darwin_amd64.tar.gz"
      sha256 "c6f8777d60ba214ae86c39c508b68f0cec53a82f0e0abaa48ecd3b9c6524cb1a"

      def install
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.0.4/helm-release-pruner_4.0.4_darwin_arm64.tar.gz"
      sha256 "eb883869b340eda152b6a1f66016284d51aed213a1a35d81f9a2b12a2aea630c"

      def install
        bin.install "helm-release-pruner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.0.4/helm-release-pruner_4.0.4_linux_amd64.tar.gz"
      sha256 "dc99055a3b8e5c8ecaa24ea330f25afc680aa4514a3bc60574e54d97feac6b72"
      def install
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.0.4/helm-release-pruner_4.0.4_linux_armv6.tar.gz"
      sha256 "56abed407952ed58d888b8f8f2358e9eca2f749433b8e0b4d06d8f647588750c"
      def install
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.0.4/helm-release-pruner_4.0.4_linux_arm64.tar.gz"
      sha256 "65d705ee813be3162c99a6aef803bf1ec42fa8303cc2dafdbb216c08b0c4efde"
      def install
        bin.install "helm-release-pruner"
      end
    end
  end

  test do
    system "#{bin}/helm-release-pruner --version"
  end
end
