# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmReleasePruner < Formula
  desc "Automatically delete old Helm releases"
  homepage ""
  version "4.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.1.0/helm-release-pruner_4.1.0_darwin_amd64.tar.gz"
      sha256 "9b38c269651852685626fe8bf56a55d75adb762c5e01534093247a32e69d4892"

      define_method(:install) do
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.1.0/helm-release-pruner_4.1.0_darwin_arm64.tar.gz"
      sha256 "aad036d5fbf02387463732fe623aa64935bd7824a986cb6c9e35ebd5d93e99fe"

      define_method(:install) do
        bin.install "helm-release-pruner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.1.0/helm-release-pruner_4.1.0_linux_amd64.tar.gz"
      sha256 "6cff5a27fa603f1d5ef2e42bc8eb0b7a1db3e843b9543961231df1615b826b4a"
      define_method(:install) do
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.1.0/helm-release-pruner_4.1.0_linux_armv6.tar.gz"
      sha256 "2b053dfc1d8062b2cfdf279e842108150dd8ecc9e0a762c72cffb31b87c06c83"
      define_method(:install) do
        bin.install "helm-release-pruner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/helm-release-pruner/releases/download/v4.1.0/helm-release-pruner_4.1.0_linux_arm64.tar.gz"
      sha256 "8da8517a30858af5eb6d865b82be0a5b9b7bf7a1169d3ce8269080d63b2c7240"
      define_method(:install) do
        bin.install "helm-release-pruner"
      end
    end
  end

  test do
    system "#{bin}/helm-release-pruner --version"
  end
end
