# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc "Reverse Lookup for Kubernetes RBAC"
  homepage "https://github.com/FairWindsOps/rbac-lookup"
  version "0.6.5"
  license "apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.5/rbac-lookup_0.6.5_Darwin_x86_64.tar.gz"
    sha256 "6b86428684c793dd43fc5470a792ac27f0cc943177bd8b4ee59fdcd7f33883d9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.5/rbac-lookup_0.6.5_Linux_x86_64.tar.gz"
    sha256 "fcedd377d09dc0553f422699035ec862789a69fb0c186c67a5a1bf541a9bd6ce"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.5/rbac-lookup_0.6.5_Linux_armv6.tar.gz"
    sha256 "62bcc45b7dd9345f841c14c8f5c03ae686d7061858f12ba1bea99cbecdc2a0a8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.5/rbac-lookup_0.6.5_Linux_arm64.tar.gz"
    sha256 "9655c28370451aa203a16038e75baec27e238c3bf96ae9d1d1d6d20ac4ae3296"
  end

  def install
    bin.install "rbac-lookup"
  end

  test do
    system "#{bin}/rbac-lookup version"
  end
end
