# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc "Reverse Lookup for Kubernetes RBAC"
  homepage "https://github.com/FairWindsOps/rbac-lookup"
  version "0.6.3"
  license "apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.3/rbac-lookup_0.6.3_Darwin_x86_64.tar.gz"
    sha256 "aa3c825d3e973fe2ed013189fea918570b1e7a1e818506f484eb2f53c08939f6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.3/rbac-lookup_0.6.3_Linux_x86_64.tar.gz"
    sha256 "6d8bb2664d27d3f104219da016665ee111ea2b30eb7a0bd0fc0e66cc50e3291d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.6.3/rbac-lookup_0.6.3_Linux_arm64.tar.gz"
    sha256 "4d1d0f7549832623b236c952671196f16b14ae59c9faa3300e32017b38ca47bb"
  end

  def install
    bin.install "rbac-lookup"
  end

  test do
    system "#{bin}/rbac-lookup version"
  end
end
