# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewTap < Formula
  desc "Reverse Lookup for Kubernetes RBAC"
  homepage "https://github.com/FairWindsOps/rbac-lookup"
  version "0.7.0"
  license "apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.7.0/rbac-lookup_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "e1f8b3de798d993d2b5d2aaf563f02f4ff823ffdb08365be73985359645b8fa6"
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.7.0/rbac-lookup_0.7.0_Darwin_arm64.tar.gz"
      sha256 "2d839a0422cc13010fb79ba6b97b4efe8829b5da8f8eb3800f8d77d1f1eac968"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.7.0/rbac-lookup_0.7.0_Linux_x86_64.tar.gz"
      sha256 "144e9d0d36d2eaed3a6870cbc91ba2ea6eb5e6c78a81fc00de76a71118fd444a"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.7.0/rbac-lookup_0.7.0_Linux_armv6.tar.gz"
      sha256 "faa3eaf0ca36efb4d83cec116d63b83abcf68f393628a2989086dc2a14525606"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.7.0/rbac-lookup_0.7.0_Linux_arm64.tar.gz"
      sha256 "42a93572bed0207bec016bcbd6dc0eaaabc93efbdbd79f98f76e1b4cd61c6c06"
    end
  end

  def install
    bin.install "rbac-lookup"
  end

  test do
    system "#{bin}/rbac-lookup version"
  end
end
