# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Insights < Formula
  desc "Command Line utility for Fairwinds Insights"
  homepage ""
  version "3.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.2.0/insights-cli_3.2.0_darwin_amd64.tar.gz"
      sha256 "9a4754ee2c3bf59d562627f0a2ed4c28eab751233277307f6132aa2a04c690d9"

      define_method(:install) do
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.2.0/insights-cli_3.2.0_darwin_arm64.tar.gz"
      sha256 "b2f4c673838f0ce18fcf28b8dce643792f31c3a1f40e918e984a3cf014ee5dc9"

      define_method(:install) do
        bin.install "insights-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.2.0/insights-cli_3.2.0_linux_amd64.tar.gz"
      sha256 "2e0af921fc30988b91479ac256a37b342996257a2f6c38d4a2f8f7117c40e3b3"
      define_method(:install) do
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.2.0/insights-cli_3.2.0_linux_armv6.tar.gz"
      sha256 "b37e1c21c88e4a3cf845fb6d6980dc3b5c5cac339769fe332dec3f4cfb4fd495"
      define_method(:install) do
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.2.0/insights-cli_3.2.0_linux_arm64.tar.gz"
      sha256 "12e334944ad4d53fa1e4294aa39ab8328f98e096ae633a59ed6d5290cddb37c6"
      define_method(:install) do
        bin.install "insights-cli"
      end
    end
  end

  test do
    system "#{bin}/insights version"
  end
end
