# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Insights < Formula
  desc "Command Line utility for Fairwinds Insights"
  homepage ""
  version "3.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.0.0/insights-cli_3.0.0_darwin_amd64.tar.gz"
      sha256 "28be2af48e9a2835e1425136c48b2e74527413c5aaf1d7108fe5f3020bd4fb47"

      def install
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.0.0/insights-cli_3.0.0_darwin_arm64.tar.gz"
      sha256 "f0b3cece6cf7f6dcbe319539b7e0f60b762d4eee4a943623792b582ba624da26"

      def install
        bin.install "insights-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.0.0/insights-cli_3.0.0_linux_amd64.tar.gz"
      sha256 "ca58ea38da32dc03aa3d7924de81259cf5bd807f819eafd7bba175418233efe8"
      def install
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.0.0/insights-cli_3.0.0_linux_armv6.tar.gz"
      sha256 "0c626eae3588f518e59c25662ec12aba0a8428f56995882aa6f6ad34da02c8ac"
      def install
        bin.install "insights-cli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/insights-cli/releases/download/v3.0.0/insights-cli_3.0.0_linux_arm64.tar.gz"
      sha256 "403732f866cf0ed5c5e7add83ee3c11614dbd6185ee237b29f728f47cfec248a"
      def install
        bin.install "insights-cli"
      end
    end
  end

  test do
    system "#{bin}/insights version"
  end
end
