# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nova < Formula
  desc "Check installed Helm charts for updates"
  homepage ""
  version "3.11.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.9/nova_3.11.9_darwin_amd64.tar.gz"
      sha256 "04d8ea8714a24b1150730100dc041fccdead5c8fc10c4c67621b26b3ed0e3128"

      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.9/nova_3.11.9_darwin_arm64.tar.gz"
      sha256 "b9cf89dcc97e4cb01daf756989fc0d118aec1b6360902810c434d3303528926d"

      def install
        bin.install "nova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.9/nova_3.11.9_linux_amd64.tar.gz"
      sha256 "a1c272030e7dbc6dd7921b02faa1d90665ac52e26a4c350de1aec083190f8b95"
      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.9/nova_3.11.9_linux_armv6.tar.gz"
      sha256 "9138397fb66ad6e4600c81f54cc3fce9a88407411e08dd2e1cbb47bf1b567882"
      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.9/nova_3.11.9_linux_arm64.tar.gz"
      sha256 "c4b79124c1bdfe4a363a84433d9c4bbc97b25519ee4f116e8e36726051de2188"
      def install
        bin.install "nova"
      end
    end
  end

  test do
    system "#{bin}/nova version"
  end
end
