# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nova < Formula
  desc "Check installed Helm charts for updates"
  homepage ""
  version "3.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.6.2/nova_3.6.2_darwin_arm64.tar.gz"
      sha256 "71b7cda1ebbfd789587acffc7ac71c498cb5b5b2e860cd4782377b4951a4ed28"

      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.6.2/nova_3.6.2_darwin_amd64.tar.gz"
      sha256 "3c9ac9cd1f76cef3401e925e9471dd530a8ef793808c36ca57eafe84a1debfa1"

      def install
        bin.install "nova"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.6.2/nova_3.6.2_linux_armv6.tar.gz"
      sha256 "9b5581f864a48cc32223a32100a21b4c1d6937b17f134c1d38b66a12717f18c9"

      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.6.2/nova_3.6.2_linux_arm64.tar.gz"
      sha256 "e0958f1422a652316c7157a1087dddf9604270c25686421a58a72862c73a6a6e"

      def install
        bin.install "nova"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/nova/releases/download/v3.6.2/nova_3.6.2_linux_amd64.tar.gz"
      sha256 "de1f934fc2760df9c8c37f3a3a6d1382011048362e23f22353ed6cf0366f042c"

      def install
        bin.install "nova"
      end
    end
  end

  test do
    system "#{bin}/nova version"
  end
end
