# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nova < Formula
  desc "Check installed Helm charts for updates"
  homepage ""
  version "3.11.1"

  on_macos do
    on_intel do
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.1/nova_3.11.1_darwin_amd64.tar.gz"
      sha256 "38b0fe9116a7dec7d9bd5bbb94bcc1cdee0ca72710d9abd37b202b1cddfd61f2"

      def install
        bin.install "nova"
      end
    end
    on_arm do
      url "https://github.com/FairwindsOps/nova/releases/download/v3.11.1/nova_3.11.1_darwin_arm64.tar.gz"
      sha256 "5dca53da9eee83a2d8aa2b9906a64ab9f5bb4f7f5277235a94c1f781de8ff477"

      def install
        bin.install "nova"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FairwindsOps/nova/releases/download/v3.11.1/nova_3.11.1_linux_amd64.tar.gz"
        sha256 "ca7b1cc547fcf6615dc0ea93b223bf8d8d00f5fb1e63c3dd9e21c2573113054a"

        def install
          bin.install "nova"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/FairwindsOps/nova/releases/download/v3.11.1/nova_3.11.1_linux_armv6.tar.gz"
        sha256 "895154f54dc20a61c50e42e2feda3c970958a47d9ecca1b423a3a56e3a44cf14"

        def install
          bin.install "nova"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FairwindsOps/nova/releases/download/v3.11.1/nova_3.11.1_linux_arm64.tar.gz"
        sha256 "933f9816a4cd4278f6b8f4750bd08a1a28e17cd68cf6c28b0143d3dc09225010"

        def install
          bin.install "nova"
        end
      end
    end
  end

  test do
    system "#{bin}/nova version"
  end
end
