# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pluto < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "5.5.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/pluto/releases/download/v5.5.1/pluto_5.5.1_darwin_arm64.tar.gz"
      sha256 "25abd1c2e4e91ad547a8788ad8c837afb25263e6aeee8de1260a9cad6fabc2fe"

      def install
        bin.install "pluto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/pluto/releases/download/v5.5.1/pluto_5.5.1_darwin_amd64.tar.gz"
      sha256 "1b26e88ec7b1c1509e68f88084d165d576e53dd044b1e247903b9ba40a236153"

      def install
        bin.install "pluto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/pluto/releases/download/v5.5.1/pluto_5.5.1_linux_armv6.tar.gz"
      sha256 "8f1f007532261aba75f3c02ecdffddab42cbca8e0ed1ba485b0b5744e66775e1"

      def install
        bin.install "pluto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/pluto/releases/download/v5.5.1/pluto_5.5.1_linux_arm64.tar.gz"
      sha256 "085b74abe6d0ec59f8076f09f6c26c8de419f68958a23b4bce8a7bc491b7414b"

      def install
        bin.install "pluto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/pluto/releases/download/v5.5.1/pluto_5.5.1_linux_amd64.tar.gz"
      sha256 "d8001f3e8a33557279450759a247f5054ad8ab18dfb84e16c758965aeaa958dd"

      def install
        bin.install "pluto"
      end
    end
  end

  test do
    system "#{bin}/pluto version"
  end
end
