# This file was generated by GoReleaser. DO NOT EDIT.
class Pluto < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "3.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/pluto/releases/download/v3.4.0/pluto_3.4.0_darwin_amd64.tar.gz"
    sha256 "6c9b8976c779d041e6feb353d05654b5b8c93ff94a6276948546eceace9becab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/pluto/releases/download/v3.4.0/pluto_3.4.0_linux_amd64.tar.gz"
      sha256 "0870088efd8b6ed7d25c01e0ce5bb912f6d66bd10266d6de49c9e7c186a30dc6"
    end
  end

  def install
    bin.install "pluto"
  end

  test do
    system "#{bin}/pluto version"
  end
end
