# This file was generated by GoReleaser. DO NOT EDIT.
class Polaris < Formula
  desc "Open Source Best Practices for Kubernetes"
  homepage ""
  version "4.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/polaris/releases/download/4.0.3/polaris_4.0.3_darwin_amd64.tar.gz"
    sha256 "71dad6a683f9fb7544eb683b9862d6e7ab84b041797a08af6482e0e151405725"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/polaris/releases/download/4.0.3/polaris_4.0.3_linux_amd64.tar.gz"
      sha256 "69663598349151fd5a389156facdbd2b74ab53f227bc1ad5698736a71ed5c513"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FairwindsOps/polaris/releases/download/4.0.3/polaris_4.0.3_linux_arm64.tar.gz"
        sha256 "e5c7d16935bcec04bb4ed1285c86d0bd0457fea3ef61d34f45d4de729dc043c9"
      else
        url "https://github.com/FairwindsOps/polaris/releases/download/4.0.3/polaris_4.0.3_linux_armv6.tar.gz"
        sha256 "f4de9d30887ac6328503f115200d7a2db9c71802e674cb06ae5131428771d436"
      end
    end
  end

  def install
    bin.install "polaris"
  end

  test do
    system "#{bin}/polaris version"
  end
end
