# This file was generated by GoReleaser. DO NOT EDIT.
class Polaris < Formula
  desc "Open Source Best Practices for Kubernetes"
  homepage ""
  version "4.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/FairwindsOps/polaris/releases/download/4.0.4/polaris_4.0.4_darwin_amd64.tar.gz"
    sha256 "095da8958c2b5ad809c17bbde6548373ff41b40dd63feff45242a39eed62b3aa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/polaris/releases/download/4.0.4/polaris_4.0.4_linux_amd64.tar.gz"
      sha256 "c94ff4a7b3ddffc98aa874bd17f7156cf7c96a8d42e485d26efc4a741ee4d2a9"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FairwindsOps/polaris/releases/download/4.0.4/polaris_4.0.4_linux_arm64.tar.gz"
        sha256 "c753b5b7a3233fce11dc2178e55b736bf0e6d4d1c2ef7ad7a7a52862b875d789"
      else
        url "https://github.com/FairwindsOps/polaris/releases/download/4.0.4/polaris_4.0.4_linux_armv6.tar.gz"
        sha256 "7d8eb4f24fd34ef713f5bc39e39e777ee6da216a3701323604717fc4dc6c125d"
      end
    end
  end

  def install
    bin.install "polaris"
  end

  test do
    system "#{bin}/polaris version"
  end
end
