# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RbacManager < Formula
  desc "Kubernetes RBAC automation controller"
  homepage ""
  version "1.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.1/rbac-manager_1.10.1_darwin_amd64.tar.gz"
      sha256 "b13dd96c3d0dbf22ea2fc527059d2a97125b5cda1cc82259b8986ee06afca86b"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.1/rbac-manager_1.10.1_darwin_arm64.tar.gz"
      sha256 "c86652dec272963dc177d4511b147fe96de27a242d0752cb6a1a8533ff512374"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.1/rbac-manager_1.10.1_linux_amd64.tar.gz"
      sha256 "eb51e7b5d19f871fe2a40ecfd17eef6593a726407a81dc27a3407bb4bd2e86e3"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.1/rbac-manager_1.10.1_linux_armv6.tar.gz"
      sha256 "8a522a4d42f818c7bcfdc479aa41118d2839e12b9581a76dc9b0682986ee9d9d"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.1/rbac-manager_1.10.1_linux_arm64.tar.gz"
      sha256 "de8190d08b1e68e2218dc8118af74ae247154dba113b32dc303f6232840ac6fa"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  test do
    assert_match "flag provided but not defined", shell_output("#{bin}/rbac-manager -not-a-goreleaser-test-flag 2>&1", 2)
  end
end
