# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RbacManager < Formula
  desc "Kubernetes RBAC automation controller"
  homepage ""
  version "1.10.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.2/rbac-manager_1.10.2_darwin_amd64.tar.gz"
      sha256 "7c7b7dafa9fd29704e271c6fbb7ea846837352664f404270e4c28c5737df7b4d"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.2/rbac-manager_1.10.2_darwin_arm64.tar.gz"
      sha256 "c456d039a4d65e6d22abd061a889408a554636e2db4adccfb3c240257c2a65ec"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.2/rbac-manager_1.10.2_linux_amd64.tar.gz"
      sha256 "280114685efe2d6148fa22c1fc47751a36b8af72bb6890b802c9f612017edfb3"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.2/rbac-manager_1.10.2_linux_armv6.tar.gz"
      sha256 "b772b552a0f4bb178d1fac816a5ec714f17998b99eb87a05dd435c005830a9a6"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.2/rbac-manager_1.10.2_linux_arm64.tar.gz"
      sha256 "c3b976f25a03f340854c3ceb00ae6bfb1ce06afed4feb23f42b23b50034463d2"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  test do
    assert_match "flag provided but not defined", shell_output("#{bin}/rbac-manager -not-a-goreleaser-test-flag 2>&1", 2)
  end
end
