# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RbacLookup < Formula
  desc "Reverse Lookup for Kubernetes RBAC"
  homepage "https://github.com/FairWindsOps/rbac-lookup"
  version "0.8.1"
  license "apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Darwin_x86_64.tar.gz"
      sha256 "b60c118e44c1b830a77f7eb7048aaa329d6a8b9f055c1702dae4ff61aa463d35"

      def install
        bin.install "rbac-lookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Darwin_arm64.tar.gz"
      sha256 "79abd40a9df19098b8e27dacc3e91c2e8899747dd018548abbfad096a4cdd7bd"

      def install
        bin.install "rbac-lookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Linux_armv6.tar.gz"
      sha256 "0800e3b0c30d81dbfe24d35555ec41bd1b09719afcdd1302de0b29a5e7656d37"

      def install
        bin.install "rbac-lookup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Linux_arm64.tar.gz"
      sha256 "d4e77e0ebf267a713913c0e53138348f8bf9df14a2fd6965755df1f54de4852f"

      def install
        bin.install "rbac-lookup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-lookup/releases/download/v0.8.1/rbac-lookup_0.8.1_Linux_x86_64.tar.gz"
      sha256 "1209a57af993d016c6a35e3e777bb278fdae81f1e8470fbcbe0d54aaee98a77b"

      def install
        bin.install "rbac-lookup"
      end
    end
  end

  test do
    system "#{bin}/rbac-lookup version"
  end
end
