# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RbacManager < Formula
  desc "Kubernetes RBAC automation controller"
  homepage ""
  version "1.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.0/rbac-manager_1.10.0_darwin_amd64.tar.gz"
      sha256 "a7b4da66ae238a46967486c64fc99ad1fc59e3c7b08d3494c43a16c1c6987f09"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.0/rbac-manager_1.10.0_darwin_arm64.tar.gz"
      sha256 "83c3caa4b95eec8617be2cc71e245b63b59060e087a12ebc1dc951d9e11359ab"

      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.0/rbac-manager_1.10.0_linux_amd64.tar.gz"
      sha256 "e14ee385526ac597635e049294116d64fd0cc79670a11b58419ab90901fe6d5b"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.0/rbac-manager_1.10.0_linux_armv6.tar.gz"
      sha256 "e3178b6d1787c36c5f4a58289df7b1aab278b47ffde3f894dbd33a3ef64c3632"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/rbac-manager/releases/download/v1.10.0/rbac-manager_1.10.0_linux_arm64.tar.gz"
      sha256 "96bc85faaf2f149eb79a26f8f1afbf7c20b8f4968d5db57bf1c2c3cf8d0470ba"
      define_method(:install) do
        bin.install "rbac-manager"
      end
    end
  end

  test do
    assert_match "flag provided but not defined", shell_output("#{bin}/rbac-manager -not-a-goreleaser-test-flag 2>&1", 2)
  end
end
