# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reckoner < Formula
  desc "Declarative Helm chart deployment using course files"
  homepage ""
  version "6.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/reckoner/releases/download/v6.3.0/reckoner_6.3.0_darwin_amd64.tar.gz"
      sha256 "4d429b0ecc993f3187079871e6fa4841837930bb18347e5a3c8c97d9c3af33ce"

      define_method(:install) do
        bin.install "reckoner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/reckoner/releases/download/v6.3.0/reckoner_6.3.0_darwin_arm64.tar.gz"
      sha256 "5f381902148a37727de8d7bc8f53dd5c9cdbd8533ebfbbf3fe384f22fbd91fd3"

      define_method(:install) do
        bin.install "reckoner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/reckoner/releases/download/v6.3.0/reckoner_6.3.0_linux_amd64.tar.gz"
      sha256 "4cb7d399386b0fcdb5be87b18b6e9d4a787da3e65afb8789542b7f7566e9d2f7"
      define_method(:install) do
        bin.install "reckoner"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/reckoner/releases/download/v6.3.0/reckoner_6.3.0_linux_armv6.tar.gz"
      sha256 "d52ce6148022945e18b0dd7faea67a50bf84dd62e8f5f6c153d461cfba6277a4"
      define_method(:install) do
        bin.install "reckoner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/reckoner/releases/download/v6.3.0/reckoner_6.3.0_linux_arm64.tar.gz"
      sha256 "babd406d43a1487a69e1f70805df026abefc2ab6ab87479ae111b698aefc79b0"
      define_method(:install) do
        bin.install "reckoner"
      end
    end
  end

  test do
    system "#{bin}/reckoner version"
  end
end
