# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saffire < Formula
  desc "Kubernetes AlternateImageSource controller"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/saffire/releases/download/v0.1.0/saffire_0.1.0_darwin_amd64.tar.gz"
      sha256 "f9e0cc77969c226481b14c9c34b651d4bb377a98dc9c1de147ce037573ac6ecf"

      define_method(:install) do
        bin.install "saffire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/saffire/releases/download/v0.1.0/saffire_0.1.0_darwin_arm64.tar.gz"
      sha256 "a495e67ad1bce68190905f9d287e70ae4dddb818b2ef63d8725d30eabcd2f1e2"

      define_method(:install) do
        bin.install "saffire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/saffire/releases/download/v0.1.0/saffire_0.1.0_linux_amd64.tar.gz"
      sha256 "efbe473612d6fba5068271a451c06aec1214728e28053b9c793f24d975c12e08"
      define_method(:install) do
        bin.install "saffire"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/saffire/releases/download/v0.1.0/saffire_0.1.0_linux_armv6.tar.gz"
      sha256 "15968f33e1ef5b813c0213e625b15c2e38e13c18186cf2876d9d88850f5b5855"
      define_method(:install) do
        bin.install "saffire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/saffire/releases/download/v0.1.0/saffire_0.1.0_linux_arm64.tar.gz"
      sha256 "28d6fc38898572bad9c7372fcbc5e1c3194871b68b7dd4dc5051a2536a59830e"
      define_method(:install) do
        bin.install "saffire"
      end
    end
  end

  test do
    assert_match "flag provided but not defined", shell_output("#{bin}/saffire -not-a-goreleaser-test-flag 2>&1", 2)
  end
end
