# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenInjector < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "1.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.2/vault-token-injector_1.8.2_darwin_amd64.tar.gz"
      sha256 "0d68c9f737e3c351d75907964aafc20a3b46f6d7427bd0cfb158ce1e78202066"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.2/vault-token-injector_1.8.2_darwin_arm64.tar.gz"
      sha256 "0f5099336626ee02df481f056232fe68f57313da32f8e561a6487d0a8b567c1e"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.2/vault-token-injector_1.8.2_linux_amd64.tar.gz"
      sha256 "161273934853c06e19bcd9f30bc7e6a1152e9ce33c22fe8be47b8fd7fdce7461"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.2/vault-token-injector_1.8.2_linux_arm64.tar.gz"
      sha256 "5d76db0d9f259b5b926f2be6fd4e83063f9198ff2469c5afdd12c9abfc658279"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.2/vault-token-injector_1.8.2_linux_armv6.tar.gz"
      sha256 "5aadac1ffa54c023a3855f8d9353d416a6de1d13acb57d1a519a0a40f794c567"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  test do
    system "#{bin}/vault-token-injector version"
  end
end
