# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenInjector < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "1.8.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.3/vault-token-injector_1.8.3_darwin_amd64.tar.gz"
      sha256 "cb47d9d13832138e9c97707da7b5b04f05e4994b285fc04c812ad110ce9afcde"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.3/vault-token-injector_1.8.3_darwin_arm64.tar.gz"
      sha256 "f5b807417793d7431fd66fef8c6fe67b67598b1313af756ccfae8ebd074eac5e"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.3/vault-token-injector_1.8.3_linux_armv6.tar.gz"
      sha256 "7d2416b05e5a76fb2a8a7557040db392fd66b8ffa01e901b7397ba5f5ae69515"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.3/vault-token-injector_1.8.3_linux_arm64.tar.gz"
      sha256 "fe668e08987b3030aaa84174394f1059a2499b0070861ea56a0634c9cfc82c63"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.8.3/vault-token-injector_1.8.3_linux_amd64.tar.gz"
      sha256 "0764790d4aaf1f95e6357071fbc9c48006ca8ca81592a54e8bb2019b233a6cc8"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  test do
    system "#{bin}/vault-token-injector version"
  end
end
