# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultTokenInjector < Formula
  desc "Detect deprecated Kubernetes apiVersions"
  homepage ""
  version "1.9.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.9.0/vault-token-injector_1.9.0_darwin_arm64.tar.gz"
      sha256 "53de2eca000fe6027dcaadb5883120c6738d11a75fe6eb44cc1afd1860b024f3"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.9.0/vault-token-injector_1.9.0_darwin_amd64.tar.gz"
      sha256 "eaed013481eb6f00f8f0a193d6ea711ee69ff09fd007cad0df03b4cb28f1ff65"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.9.0/vault-token-injector_1.9.0_linux_arm64.tar.gz"
      sha256 "e490ecdeac8732e6d2024c42289b716a6068a7650af8a9a40601f1ed9f3868c7"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.9.0/vault-token-injector_1.9.0_linux_armv6.tar.gz"
      sha256 "b216d79ba2cdfe78f2ca4dbbef10f12403fee8690d62cf9bbc3e4915d4c03f8b"

      def install
        bin.install "vault-token-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FairwindsOps/vault-token-injector/releases/download/v1.9.0/vault-token-injector_1.9.0_linux_amd64.tar.gz"
      sha256 "dbf75666a85e7395f8144f64852d7c51badda4997951499b482194253ea28174"

      def install
        bin.install "vault-token-injector"
      end
    end
  end

  test do
    system "#{bin}/vault-token-injector version"
  end
end
